<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Before launch application]]>
    </line>
    <line>
      <![CDATA[Application launched successfully]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="27289" started-at="2022-12-17T11:31:28Z" finished-at="2022-12-17T11:31:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27289" started-at="2022-12-17T11:31:28Z" finished-at="2022-12-17T11:31:55Z">
      <class name="com.prm.testcase.LoginFunctinality">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.prm.testcase.LoginFunctinality@4b952a2d]" name="setUp" is-config="true" duration-ms="15052" started-at="2022-12-17T11:31:28Z" finished-at="2022-12-17T11:31:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyTest()[pri:0, instance:com.prm.testcase.LoginFunctinality@4b952a2d]" name="verifyTest" duration-ms="12" started-at="2022-12-17T11:31:43Z" finished-at="2022-12-17T11:31:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.prm.testcase.LoginFunctinality.verifyTest(LoginFunctinality.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.prm.testcase.LoginFunctinality@4b952a2d]" name="tearDown" is-config="true" duration-ms="1466" started-at="2022-12-17T11:31:43Z" finished-at="2022-12-17T11:31:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyTest status=FAILURE method=LoginFunctinality.verifyTest()[pri:0, instance:com.prm.testcase.LoginFunctinality@4b952a2d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.prm.testcase.LoginFunctinality@4b952a2d]" name="setUp" is-config="true" duration-ms="6644" started-at="2022-12-17T11:31:44Z" finished-at="2022-12-17T11:31:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyValidLogin()[pri:0, instance:com.prm.testcase.LoginFunctinality@4b952a2d]" name="verifyValidLogin" duration-ms="2884" started-at="2022-12-17T11:31:51Z" finished-at="2022-12-17T11:31:54Z">
          <reporter-output>
            <line>
              <![CDATA[Before launch application]]>
            </line>
            <line>
              <![CDATA[Application launched successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyValidLogin -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.prm.testcase.LoginFunctinality@4b952a2d]" name="tearDown" is-config="true" duration-ms="1106" started-at="2022-12-17T11:31:54Z" finished-at="2022-12-17T11:31:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyValidLogin status=SUCCESS method=LoginFunctinality.verifyValidLogin()[pri:0, instance:com.prm.testcase.LoginFunctinality@4b952a2d] output=Before launch application]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.prm.testcase.LoginFunctinality -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
